version: '3'
services:
  node:
    build: ./server
    command: node /app/server.js
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    depends_on:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=parol
  # vue:
  #   build: ./client
  #   command: npm run serve
  #   ports:
  #   - "8080:8080"
  #   volumes:
  #   - ./client:/app